#!/usr/bin/env python3
"""
keycloak-enum.py  —  Keycloak version detection

No installation required. Python 3.9+ stdlib only.
A fingerprints.json file must be present next to this script
(bundled in the repo, or build one yourself with: collect --all).

Usage
-----
  # Probe a live target:
  python3 keycloak-enum.py fingerprint https://keycloak.example.com
  python3 keycloak-enum.py fingerprint https://keycloak.example.com --no-verify

  # Add / update fingerprints from a Docker image (requires docker CLI):
  python3 keycloak-enum.py collect 26.7.1
  python3 keycloak-enum.py collect --all            # all known versions

  # Import from an existing SQLite database (generated by the full package):
  python3 keycloak-enum.py export-db data/fingerprints.sqlite

Global options
--------------
  --db PATH     Path to fingerprints.json  [default: fingerprints.json next to this script]
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import ssl
import subprocess
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
import zipfile
import threading
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import date
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

TOOL_VERSION = "1.0.0"
USER_AGENT = f"keycloak-fingerprint/{TOOL_VERSION} (https://github.com/lvetter/Keycloak-Enum)"
DEFAULT_DB = Path(__file__).parent / "fingerprints.json"

KC_IMAGE = "quay.io/keycloak/keycloak:{version}"

# All versions included in the bundled fingerprints.json
KNOWN_VERSIONS = [
    # 24.x  (24.0.3 was never released)
    "24.0.0", "24.0.1", "24.0.2", "24.0.3", "24.0.4", "24.0.5",
    # 25.x  (25.0.3 was never released)
    "25.0.0", "25.0.1", "25.0.2", "25.0.4", "25.0.5", "25.0.6",
    # 26.0.x  (26.0.3 was never released)
    "26.0.0", "26.0.1", "26.0.2", "26.0.4", "26.0.5", "26.0.6", "26.0.7", "26.0.8",
    # 26.1.x
    "26.1.0", "26.1.1", "26.1.2", "26.1.3", "26.1.4", "26.1.5",
    # 26.2.x
    "26.2.0", "26.2.1", "26.2.2", "26.2.3", "26.2.4", "26.2.5",
    # 26.3.x
    "26.3.0", "26.3.1", "26.3.2", "26.3.3", "26.3.4", "26.3.5",
    # 26.4.x  (26.4.3 was never released)
    "26.4.0", "26.4.1", "26.4.2", "26.4.4", "26.4.5", "26.4.6", "26.4.7",
    # 26.5.x
    "26.5.0", "26.5.1", "26.5.2", "26.5.3", "26.5.4", "26.5.5", "26.5.6", "26.5.7",
    # 26.6.x
    "26.6.0", "26.6.1", "26.6.2", "26.6.3", "26.6.4",
    # 26.7.x
    "26.7.0",
]

# Resource URL prefixes — try without /auth/ first (26.x default)
_PREFIXES = ["/resources/", "/auth/resources/"]

# Vendor JS paths (relative to /resources/<hash>/)
# Served publicly without authentication on all supported versions.
_VENDOR_PATHS = [
    "common/keycloak/vendor/web-crypto-shim/web-crypto-shim.js",  # changed in 26.7.0
    "common/keycloak/vendor/react/react.production.min.js",
    "common/keycloak/vendor/react/react-jsx-runtime.production.min.js",
    "common/keycloak/vendor/react-dom/react-dom.production.min.js",
    "common/keycloak/vendor/rfc4648/rfc4648.js",
]

# SPA Vite manifest subpaths — probed using the login resource hash when the
# account or admin console redirects to the login page.
_SPA_SUBPATHS = ["/account/keycloak.v3", "/admin/keycloak.v2"]

# Console probe paths — ordered from most to least discriminating
_PROBE_PATHS = [
    "/admin/master/console/",
    "/auth/admin/master/console/",
    "/realms/master/account/",
    "/auth/realms/master/account/",
    "/auth/realms/master/",
    "/realms/master/",
    "/auth/",
    "/",
]

# JAR targets for Docker image collection
# (grep_term, vite_manifest_in_jar, resources_dir_in_jar, label)
_JAR_TARGETS = [
    (
        "keycloak-admin-ui",
        "theme/keycloak.v2/admin/resources/.vite/manifest.json",
        "theme/keycloak.v2/admin/resources/",
        "admin-ui",
    ),
    (
        "keycloak-account-ui",
        "theme/keycloak.v3/account/resources/.vite/manifest.json",
        "theme/keycloak.v3/account/resources/",
        "account-ui",
    ),
]

# Specific files to collect from keycloak-themes.jar.
# Also serves as a fallback for ≤26.0.x where vendor JS lives in themes.jar
# (the separate keycloak-themes-vendor.jar was introduced in 26.1.0).
_LOGIN_THEME_FILES = frozenset({
    "theme/keycloak.v2/login/resources/css/styles.css",
    "theme/keycloak.v2/login/resources/js/password-policy.js",
    "theme/keycloak.v2/login/resources/js/userProfile.js",
    "theme/keycloak/login/resources/css/login.css",
    # Vendor JS — present in themes.jar for ≤26.0.x; absent in 26.1.0+
    "theme/keycloak/common/resources/vendor/react/react.production.min.js",
    "theme/keycloak/common/resources/vendor/react/react-jsx-runtime.production.min.js",
    "theme/keycloak/common/resources/vendor/react-dom/react-dom.production.min.js",
    "theme/keycloak/common/resources/vendor/rfc4648/rfc4648.js",
    "theme/keycloak/common/resources/vendor/web-crypto-shim/web-crypto-shim.js",
})

# Files to collect from keycloak-themes-vendor.jar (26.1.0+)
_THEMES_VENDOR_FILES = frozenset({
    "theme/keycloak/common/resources/vendor/web-crypto-shim/web-crypto-shim.js",
    "theme/keycloak/common/resources/vendor/react/react.production.min.js",
    "theme/keycloak/common/resources/vendor/react/react-jsx-runtime.production.min.js",
    "theme/keycloak/common/resources/vendor/react-dom/react-dom.production.min.js",
    "theme/keycloak/common/resources/vendor/rfc4648/rfc4648.js",
})


# ─────────────────────────────────────────────────────────────────────────────
# HTTP helpers
# ─────────────────────────────────────────────────────────────────────────────

def http_get(url: str, *, verify: bool = True, timeout: float = 15) -> tuple[bytes, int]:
    """GET *url*, return (body_bytes, http_status_code). Raises on network error."""
    ctx = ssl.create_default_context()
    if not verify:
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
    opener = urllib.request.build_opener(
        urllib.request.HTTPSHandler(context=ctx),
        urllib.request.HTTPRedirectHandler(),
    )
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with opener.open(req, timeout=timeout) as resp:
            return resp.read(), resp.status
    except urllib.error.HTTPError as e:
        try:
            return e.read(), e.code
        except Exception:
            return b"", e.code


# ─────────────────────────────────────────────────────────────────────────────
# Hashing
# ─────────────────────────────────────────────────────────────────────────────

def sha256hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


# ─────────────────────────────────────────────────────────────────────────────
# Progress bar
# ─────────────────────────────────────────────────────────────────────────────

_PROGRESS_LOCK = threading.Lock()


def _progress(done: int, total: int, label: str = "chunks") -> None:
    """Overwrite the current stderr line with a progress bar (TTY only)."""
    if not sys.stderr.isatty():
        return
    width = 28
    filled = int(width * done / total) if total else width
    bar = "\u2588" * filled + "\u2591" * (width - filled)
    with _PROGRESS_LOCK:
        sys.stderr.write(f"\r  [{bar}] {done}/{total}  {label}  ")
        sys.stderr.flush()


def _clear_progress() -> None:
    """Erase the progress bar line from stderr."""
    if not sys.stderr.isatty():
        return
    with _PROGRESS_LOCK:
        sys.stderr.write(f"\r{' ' * 70}\r")
        sys.stderr.flush()


# ─────────────────────────────────────────────────────────────────────────────
# Fingerprint database  (fingerprints.json)
# ─────────────────────────────────────────────────────────────────────────────

def load_db(path: Path) -> dict[str, list[str]]:
    """Load fingerprints.json → {version: [sha256, ...]}"""
    if not path.exists():
        return {}
    with open(path) as f:
        raw = json.load(f)
    return {k: v for k, v in raw.items() if not k.startswith("_")}


def save_db(db: dict[str, list[str]], path: Path) -> None:
    """Save {version: [sha256, ...]} to fingerprints.json."""
    total = sum(len(v) for v in db.values())
    out: dict = {
        "_meta": {
            "generated": str(date.today()),
            "tool": f"keycloak-fingerprint/{TOOL_VERSION}",
            "versions": len(db),
            "total_hashes": total,
        }
    }
    out.update({k: sorted(set(v)) for k, v in sorted(db.items())})
    with open(path, "w") as f:
        json.dump(out, f, separators=(",", ":"))
        f.write("\n")
    print(f"Saved {len(db)} versions, {total} hashes → {path}")


def build_index(db: dict[str, list[str]]) -> dict[str, list[str]]:
    """Build inverse lookup: sha256 → [version, ...] for O(1) matching."""
    idx: dict[str, list[str]] = defaultdict(list)
    for ver, hashes in db.items():
        for h in hashes:
            idx[h].append(ver)
    return dict(idx)


# ─────────────────────────────────────────────────────────────────────────────
# HTML parsing helpers
# ─────────────────────────────────────────────────────────────────────────────

_RE_RESOURCE_HASH = re.compile(r"/(?:auth/)?resources/([a-zA-Z0-9]{3,12})/")
_RE_SCRIPT_SRC = re.compile(r'<script[^>]+src=["\']([^"\']+\.js[^"\']*)["\']', re.I)
_RE_LINK_HREF = re.compile(r'<link[^>]+href=["\']([^"\']+\.css[^"\']*)["\']', re.I)


def is_keycloak_page(html: str) -> bool:
    """Return True if *html* contains Keycloak resource URLs."""
    return bool(_RE_RESOURCE_HASH.search(html))


def extract_resource_hash(html: str) -> str | None:
    m = _RE_RESOURCE_HASH.search(html)
    return m.group(1) if m else None


def extract_asset_urls(html: str, origin: str) -> list[str]:
    """Return absolute Vite SPA entry asset URLs found in the HTML."""
    parsed = urllib.parse.urlparse(origin)
    host = f"{parsed.scheme}://{parsed.netloc}"
    urls = []
    for m in list(_RE_SCRIPT_SRC.finditer(html)) + list(_RE_LINK_HREF.finditer(html)):
        url = m.group(1)
        if url.startswith("//"):
            url = parsed.scheme + ":" + url
        elif url.startswith("/"):
            url = host + url
        elif not url.startswith("http"):
            url = origin.rstrip("/") + "/" + url
        # Only include Vite content-hashed SPA entry files (not vendor CSS, etc.)
        if "/assets/main-" in url or "/assets/index-" in url:
            urls.append(url)
    return urls


def resource_base_from_asset_url(asset_url: str) -> str | None:
    """Strip '/assets/<file>' suffix to get the Vite resource base URL."""
    idx = asset_url.find("/assets/")
    return asset_url[:idx] if idx != -1 else None


# ─────────────────────────────────────────────────────────────────────────────
# Vite manifest fetching
# ─────────────────────────────────────────────────────────────────────────────

def fetch_vite_hashes(
    resource_base: str,
    *,
    verify: bool = True,
    timeout: float = 15,
    workers: int = 20,
    show_progress: bool = False,
    label: str = "chunks",
) -> list[str]:
    """Fetch .vite/manifest.json and return sha256 hashes of all chunk JS/CSS.

    Asset downloads are parallelised with *workers* threads so that even
    200-chunk SPAs complete in a few seconds instead of minutes.
    """
    manifest_url = resource_base.rstrip("/") + "/.vite/manifest.json"
    try:
        body, status = http_get(manifest_url, verify=verify, timeout=timeout)
        if status != 200:
            return []
        manifest: dict = json.loads(body.decode("utf-8"))
    except Exception:
        return []

    assets_base = resource_base.rstrip("/") + "/assets/"
    seen: set[str] = set()
    urls: list[str] = []

    for meta in manifest.values():
        for rel in [meta.get("file", "")] + meta.get("css", []):
            if not rel:
                continue
            if rel.rsplit(".", 1)[-1].lower() not in ("js", "css"):
                continue
            url = assets_base + rel.split("/")[-1]
            if url not in seen:
                seen.add(url)
                urls.append(url)

    def _fetch_one(url: str) -> str | None:
        try:
            fbody, fstatus = http_get(url, verify=verify, timeout=timeout)
            if fstatus == 200 and fbody:
                return sha256hex(fbody)
        except Exception:
            pass
        return None

    hashes: list[str] = []
    total = len(urls)
    show = show_progress and total > 3
    done = 0

    with ThreadPoolExecutor(max_workers=min(workers, total or 1)) as pool:
        futures = {pool.submit(_fetch_one, url): url for url in urls}
        for future in as_completed(futures):
            done += 1
            if show:
                _progress(done, total, label)
            result = future.result()
            if result:
                hashes.append(result)

    if show:
        _clear_progress()

    return hashes


# ─────────────────────────────────────────────────────────────────────────────
# Vendor JS fetching
# ─────────────────────────────────────────────────────────────────────────────

def fetch_vendor_hashes(
    host: str,
    resource_hash: str,
    *,
    verify: bool = True,
    timeout: float = 15,
) -> list[str]:
    """Fetch login-theme vendor JS files, return sha256 hashes."""
    hashes = []
    for rel_path in _VENDOR_PATHS:
        for prefix in _PREFIXES:
            url = host + prefix + resource_hash + "/" + rel_path
            try:
                body, status = http_get(url, verify=verify, timeout=timeout)
                if status == 200 and body:
                    hashes.append(sha256hex(body))
                    break
            except Exception:
                pass
    return hashes


# ─────────────────────────────────────────────────────────────────────────────
# Hash matching
# ─────────────────────────────────────────────────────────────────────────────

def match_hashes(sha256s: list[str], index: dict[str, list[str]]) -> dict:
    """Intersect all hash lookups and return a match result dict."""
    total = len(sha256s)
    if not sha256s:
        return _mr("unknown", [], "unknown", "No assets downloaded.", 0, 0)

    version_sets: list[set[str]] = []
    matched = 0
    for h in sha256s:
        vs = set(index.get(h, []))
        if vs:
            version_sets.append(vs)
            matched += 1

    if not version_sets:
        return _mr(
            "unknown", [], "unknown",
            f"None of the {total} observed hashes matched the database.\n"
            "The version may not be in the database yet. Try: collect <version>",
            0, total,
        )

    # Intersect — the result is the set of versions that contain ALL matched hashes
    intersection = version_sets[0].copy()
    for s in version_sets[1:]:
        intersection &= s
        if not intersection:
            break

    candidates = sorted(intersection)

    if not candidates:
        # Individual hashes hit the DB but no single version contains all of them —
        # can happen with CDN caches or mixed builds.
        union = sorted(set().union(*version_sets))
        return _mr(
            "partial", union, "low",
            f"{matched}/{total} hashes found in database but share no common version.\n"
            f"Possible candidates: {', '.join(union[:6])}{'…' if len(union) > 6 else ''}",
            matched, total,
        )

    confidence = "high" if matched >= 5 else "medium"

    if len(candidates) == 1:
        return _mr(
            "exact_unique", candidates, confidence,
            f"{matched}/{total} hashes uniquely identify Keycloak {candidates[0]}.",
            matched, total,
        )

    return _mr(
        "exact_ambiguous", candidates, "medium" if matched >= 5 else "low",
        f"{matched}/{total} hashes matched {len(candidates)} versions: "
        f"{', '.join(candidates)}.\n"
        "Exact patch cannot be determined from the publicly available assets alone.",
        matched, total,
    )


def _mr(status, versions, confidence, explanation, matched, total):
    return dict(status=status, versions=versions, confidence=confidence,
                explanation=explanation, matched=matched, total=total)


# ─────────────────────────────────────────────────────────────────────────────
# Main fingerprinting flow
# ─────────────────────────────────────────────────────────────────────────────

def fingerprint_target(
    target: str,
    index: dict[str, list[str]],
    *,
    verify: bool = True,
    timeout: float = 15,
    verbose: bool = False,
) -> dict:
    """Probe *target* and return a result dict."""
    if not target.startswith(("http://", "https://")):
        target = "https://" + target
    target = target.rstrip("/")
    parsed = urllib.parse.urlparse(target)
    host = f"{parsed.scheme}://{parsed.netloc}"

    def dbg(msg: str) -> None:
        if verbose:
            print(f"  [*] {msg}", file=sys.stderr)

    hashes: list[str] = []
    console_url: str | None = None
    resource_hash: str | None = None
    first_js: str | None = None
    first_css: str | None = None
    detected = False

    # ── Step 1: Probe console / login paths ──────────────────────────────────
    for path in _PROBE_PATHS:
        url = host + path
        try:
            body, status = http_get(url, verify=verify, timeout=timeout)
        except Exception as e:
            dbg(f"{path} → network error: {e}")
            continue

        html = body.decode("utf-8", errors="replace")
        dbg(f"{path} → HTTP {status}, keycloak={is_keycloak_page(html)}")
        if not is_keycloak_page(html):
            continue

        detected = True
        console_url = url
        resource_hash = extract_resource_hash(html)
        dbg(f"Keycloak detected, resource_hash={resource_hash}")

        # ── Step 2: Fetch entry assets listed in HTML ─────────────────────
        for asset_url in extract_asset_urls(html, host):
            try:
                abody, astatus = http_get(asset_url, verify=verify, timeout=timeout)
                if astatus == 200 and abody:
                    h = sha256hex(abody)
                    hashes.append(h)
                    fname = asset_url.split("/")[-1]
                    if asset_url.endswith(".js") and not first_js:
                        first_js = fname
                    if asset_url.endswith(".css") and not first_css:
                        first_css = fname
                    dbg(f"  {fname} → {h[:16]}")

                    # ── Step 3: Vite manifest → all chunk files ───────────
                    resource_base = resource_base_from_asset_url(asset_url)
                    if resource_base:
                        chunk_hashes = fetch_vite_hashes(
                            resource_base, verify=verify, timeout=timeout,
                            show_progress=not verbose, label="chunks",
                        )
                        dbg(f"  Vite chunks: {len(chunk_hashes)} hashes")
                        hashes.extend(chunk_hashes)
            except Exception as e:
                dbg(f"  asset fetch failed: {e}")

        break  # stop after first Keycloak page found

    if not detected:
        return {
            "target": target,
            "detected": False,
            "explanation": "Keycloak not detected at any probed path.",
        }

    # ── Step 4: Vendor JS via login resource hash ─────────────────────────────
    if resource_hash:
        vendor_hashes = fetch_vendor_hashes(host, resource_hash, verify=verify, timeout=timeout)
        dbg(f"Vendor JS: {len(vendor_hashes)}/{len(_VENDOR_PATHS)} fetched")
        hashes.extend(vendor_hashes)

        # ── Step 5: Probe SPA Vite manifests via login resource hash ─────────
        # The account console (/realms/master/account/) often redirects to the
        # OIDC login page, so the SPA HTML is never served and Step 2 yields no
        # Vite chunks.  All /resources/<hash>/... paths are served publicly, so
        # we can fetch the manifest directly and get version-unique chunk hashes.
        # This resolves patch-level ambiguity within a minor version series
        # (e.g., 26.2.0 vs 26.2.5 which share all login-theme and vendor assets).
        # Both SPA subpaths are independent — probe them in parallel.
        def _probe_spa(spa_sub: str) -> tuple[str, list[str]]:
            lbl = spa_sub.split(".")[-1] + " chunks"  # "v3 chunks" / "v2 chunks"
            for prefix in _PREFIXES:
                spa_base = host + prefix + resource_hash + spa_sub
                chunk_hashes = fetch_vite_hashes(
                    spa_base, verify=verify, timeout=timeout,
                    show_progress=not verbose, label=lbl,
                )
                if chunk_hashes:
                    return spa_sub, chunk_hashes
            return spa_sub, []

        with ThreadPoolExecutor(max_workers=len(_SPA_SUBPATHS)) as pool:
            for spa_sub, chunk_hashes in pool.map(_probe_spa, _SPA_SUBPATHS):
                if chunk_hashes:
                    dbg(f"SPA manifest ({spa_sub.split('/')[-1]}): {len(chunk_hashes)} hashes")
                    hashes.extend(chunk_hashes)

    # ── Step 6: Match ─────────────────────────────────────────────────────────
    unique_hashes = list(dict.fromkeys(h for h in hashes if h))
    result = match_hashes(unique_hashes, index)

    return {
        "target": target,
        "console_url": console_url,
        "detected": True,
        "resource_hash": resource_hash,
        "first_js": first_js,
        "first_css": first_css,
        "hashes_checked": len(unique_hashes),
        **result,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Docker collection helpers
# ─────────────────────────────────────────────────────────────────────────────

def _list_jars_in_container(container_id: str) -> list[str]:
    """Return paths of all JAR files inside *container_id* (one docker export)."""
    docker_proc = subprocess.Popen(
        ["docker", "export", container_id],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    tar_proc = subprocess.Popen(
        ["tar", "-t"],
        stdin=docker_proc.stdout,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    docker_proc.stdout.close()  # allow docker_proc to receive SIGPIPE if tar exits
    out, _ = tar_proc.communicate()
    docker_proc.wait()
    lines = out.decode("utf-8", errors="replace").splitlines()
    return ["/" + l.lstrip("./") for l in lines if l.endswith(".jar")]


def _pick_jar(jar_list: list[str], grep_term: str, exclude: str | None = None) -> str | None:
    hits = [p for p in jar_list if grep_term in p]
    if exclude:
        hits = [p for p in hits if exclude not in p]
    return hits[0] if hits else None


def _copy_jar(container_id: str, jar_path: str) -> bytes | None:
    """Copy a JAR from a container to memory. Returns bytes or None."""
    with tempfile.NamedTemporaryFile(suffix=".jar", delete=False) as tmp:
        tmp_path = Path(tmp.name)
    try:
        r = subprocess.run(
            ["docker", "cp", f"{container_id}:{jar_path}", str(tmp_path)],
            capture_output=True,
        )
        return tmp_path.read_bytes() if r.returncode == 0 else None
    except Exception:
        return None
    finally:
        tmp_path.unlink(missing_ok=True)


def _hash_vite_jar(jar_bytes: bytes, manifest_path: str, resources_dir: str) -> list[str]:
    """Hash all Vite JS/CSS assets in an admin-ui or account-ui JAR."""
    hashes = []
    with zipfile.ZipFile(io.BytesIO(jar_bytes)) as zf:
        names = set(zf.namelist())
        if manifest_path in names:
            # Vite build (KC 24+): use manifest for exact asset enumeration
            manifest: dict = json.loads(zf.read(manifest_path).decode("utf-8"))
            seen: set[str] = set()
            for meta in manifest.values():
                for rel in [meta.get("file", "")] + meta.get("css", []):
                    if not rel:
                        continue
                    ext = rel.rsplit(".", 1)[-1].lower()
                    if ext not in ("js", "css"):
                        continue
                    full = resources_dir + rel
                    if full not in seen and full in names:
                        seen.add(full)
                        hashes.append(sha256hex(zf.read(full)))
        else:
            # Pre-Vite (Webpack era, KC ≤23): hash all JS/CSS under resources
            assets_prefix = resources_dir + "assets/"
            for name in names:
                if name.startswith(assets_prefix) and name.endswith((".js", ".css")):
                    hashes.append(sha256hex(zf.read(name)))
    return hashes


def _hash_theme_files(jar_bytes: bytes, file_set: frozenset[str]) -> list[str]:
    """Hash specific named files from a themes JAR."""
    hashes = []
    with zipfile.ZipFile(io.BytesIO(jar_bytes)) as zf:
        names = set(zf.namelist())
        for path in file_set:
            if path in names:
                hashes.append(sha256hex(zf.read(path)))
    return hashes


def collect_version(
    version: str,
    db: dict[str, list[str]],
    *,
    image: str | None = None,
    force: bool = False,
) -> bool:
    """Collect fingerprints for one Keycloak version. Updates *db* in place."""
    if version in db and not force:
        print(f"  {version}: already in database, skipping (use --force to redo)")
        return True

    img = image or KC_IMAGE.format(version=version)
    sys.stdout.write(f"  {version}  ({img}) …")
    sys.stdout.flush()

    # Pull image quietly in case it's not cached
    subprocess.run(["docker", "pull", "-q", img], capture_output=True)

    r = subprocess.run(["docker", "create", img], capture_output=True, text=True)
    if r.returncode != 0:
        print(f"  FAILED — could not create container: {r.stderr.strip()}")
        return False

    container_id = r.stdout.strip()
    all_hashes: list[str] = []

    try:
        # Get the full JAR file list with a single docker export
        sys.stdout.write(" listing…")
        sys.stdout.flush()
        jar_paths = _list_jars_in_container(container_id)

        # Admin-ui and account-ui JARs (Vite SPAs)
        for grep_term, manifest_path, resources_dir, label in _JAR_TARGETS:
            jar_path = _pick_jar(jar_paths, grep_term)
            if not jar_path:
                sys.stdout.write(f" [{label}:–]")
                sys.stdout.flush()
                continue
            jar_bytes = _copy_jar(container_id, jar_path)
            if not jar_bytes:
                continue
            h = _hash_vite_jar(jar_bytes, manifest_path, resources_dir)
            all_hashes.extend(h)
            sys.stdout.write(f" [{label}:{len(h)}]")
            sys.stdout.flush()

        # Login-theme CSS/JS from keycloak-themes.jar
        # Also picks up vendor JS for ≤26.0.x (before the vendor JAR was split out)
        themes_path = _pick_jar(jar_paths, "keycloak-themes", exclude="keycloak-themes-vendor")
        if themes_path:
            jar_bytes = _copy_jar(container_id, themes_path)
            if jar_bytes:
                h = _hash_theme_files(jar_bytes, _LOGIN_THEME_FILES)
                all_hashes.extend(h)
                sys.stdout.write(f" [themes:{len(h)}]")
                sys.stdout.flush()

        # Vendor JAR: keycloak-themes-vendor.jar (introduced in 26.1.0)
        vendor_path = _pick_jar(jar_paths, "keycloak-themes-vendor")
        if vendor_path:
            jar_bytes = _copy_jar(container_id, vendor_path)
            if jar_bytes:
                h = _hash_theme_files(jar_bytes, _THEMES_VENDOR_FILES)
                all_hashes.extend(h)
                sys.stdout.write(f" [vendor:{len(h)}]")
                sys.stdout.flush()

        unique = list(set(all_hashes))
        db[version] = unique
        print(f"  →  {len(unique)} hashes ✓")
        return True

    except Exception as e:
        print(f"  ERROR: {e}")
        return False
    finally:
        subprocess.run(["docker", "rm", container_id], capture_output=True)


# ─────────────────────────────────────────────────────────────────────────────
# CLI commands
# ─────────────────────────────────────────────────────────────────────────────

def cmd_fingerprint(args) -> int:
    db_path = Path(args.db)
    db = load_db(db_path)
    if not db:
        print(f"ERROR: fingerprint database not found at {db_path}", file=sys.stderr)
        print("Build one with:  python3 keycloak-enum.py collect --all", file=sys.stderr)
        return 1

    index = build_index(db)
    result = fingerprint_target(
        args.url, index,
        verify=not args.no_verify,
        timeout=args.timeout,
        verbose=args.verbose,
    )

    W = 12  # label width
    print()
    print(f"{'Target':{W}}: {result['target']}")
    if result.get("console_url"):
        print(f"{'Console':{W}}: {result['console_url']}")
    kc_detected = result.get("detected", False)
    print(f"{'Keycloak':{W}}: {'Detected' if kc_detected else 'Not detected'}")

    if not kc_detected:
        print(f"\n{result.get('explanation', '')}")
        return 0

    print()
    if result.get("first_js"):
        print(f"{'JavaScript':{W}}: {result['first_js']}")
    if result.get("first_css"):
        print(f"{'CSS':{W}}: {result['first_css']}")

    status = result.get("status", "unknown")
    versions = result.get("versions", [])
    confidence = result.get("confidence", "unknown")
    matched = result.get("matched", 0)
    total = result.get("hashes_checked", 0)

    status_label = {
        "exact_unique":    "exact_unique",
        "exact_ambiguous": "exact_ambiguous",
        "partial":         "partial",
        "unknown":         "unknown",
    }.get(status, status)

    print()
    print(f"{'Match':{W}}: {status_label}")
    print(f"{'Confidence':{W}}: {confidence}")
    if versions:
        label = "Version" if len(versions) == 1 else "Version(s)"
        print(f"{label:{W}}: {', '.join(versions)}")
    print()
    print(result.get("explanation", ""))

    if args.json_output:
        print()
        print(json.dumps(result, indent=2))

    return 0


def cmd_collect(args) -> int:
    db_path = Path(args.db)
    db = load_db(db_path)

    if args.all:
        versions = KNOWN_VERSIONS
    elif args.version:
        versions = [args.version]
    else:
        print("ERROR: specify a version or --all", file=sys.stderr)
        return 1

    print(f"Collecting {len(versions)} version(s) into {db_path}")
    ok = fail = 0
    for ver in versions:
        image = args.image if len(versions) == 1 else None
        if collect_version(ver, db, image=image, force=args.force):
            ok += 1
        else:
            fail += 1

    print(f"\nDone: {ok} succeeded, {fail} failed.")
    save_db(db, db_path)
    return 0 if fail == 0 else 1


def cmd_export_db(args) -> int:
    """Import an existing SQLite fingerprint database into fingerprints.json."""
    try:
        import sqlite3
    except ImportError:
        print("ERROR: sqlite3 not available", file=sys.stderr)
        return 1

    sqlite_path = Path(args.sqlite)
    if not sqlite_path.exists():
        print(f"ERROR: {sqlite_path} not found", file=sys.stderr)
        return 1

    conn = sqlite3.connect(str(sqlite_path))
    rows = conn.execute(
        "SELECT b.version, a.sha256 FROM assets a JOIN builds b ON a.build_id = b.id"
    ).fetchall()
    conn.close()

    db: dict[str, list[str]] = {}
    for version, sha256 in rows:
        db.setdefault(version, []).append(sha256)

    db_path = Path(args.db)
    save_db(db, db_path)
    print(f"Exported {len(rows)} records for {len(db)} versions from {sqlite_path}")
    return 0



# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        prog="keycloak-fingerprint",
        description="Detect Keycloak version",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--db", default=str(DEFAULT_DB), metavar="PATH",
        help="Path to fingerprints.json  [%(default)s]",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {TOOL_VERSION}")

    sub = parser.add_subparsers(dest="command", required=True)

    # ── fingerprint ──────────────────────────────────────────────────────────
    fp = sub.add_parser("fingerprint", aliases=["fp"],
                        help="Probe a live Keycloak instance and identify its version")
    fp.add_argument("url", help="Target URL  (e.g. https://keycloak.example.com)")
    fp.add_argument("--no-verify", action="store_true",
                    help="Disable TLS certificate verification")
    fp.add_argument("--timeout", type=float, default=15, metavar="SECS",
                    help="HTTP timeout in seconds  [%(default)s]")
    fp.add_argument("--verbose", "-v", action="store_true",
                    help="Print debug output to stderr")
    fp.add_argument("--json", dest="json_output", action="store_true",
                    help="Also print the full result as JSON")

    # ── collect ──────────────────────────────────────────────────────────────
    col = sub.add_parser("collect",
                         help="Collect fingerprints from a Keycloak Docker image (needs docker)")
    col.add_argument("version", nargs="?", metavar="VERSION",
                     help="Keycloak version to collect  (e.g. 26.7.1)")
    col.add_argument("--all", action="store_true",
                     help="Collect all versions in the built-in list")
    col.add_argument("--force", action="store_true",
                     help="Re-collect even if already in the database")
    col.add_argument("--image", metavar="IMAGE",
                     help="Custom Docker image  (single-version only)")

    # ── export-db ────────────────────────────────────────────────────────────
    exp = sub.add_parser("export-db",
                         help="Import from an existing keycloak-fingerprint SQLite database")
    exp.add_argument("sqlite", metavar="SQLITE_FILE",
                     help="Path to fingerprints.sqlite  (e.g. data/fingerprints.sqlite)")

    args = parser.parse_args()

    dispatch = {
        "fingerprint": cmd_fingerprint,
        "fp":          cmd_fingerprint,
        "collect":     cmd_collect,
        "export-db":   cmd_export_db,
    }
    return dispatch[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
